### ISSUE TITLE
`pubspec_overrides.yaml` not supported

### ISSUE THREAD

**Issue by mosuem** [bmw-tech/dart_apitool#148]
**Describe the bug**
Since [this pull request](https://github.com/dart-lang/pub/pull/3215), a separate `pubspec_overrides.yaml` file can exist in a repo. The `diff` tool does not read this file, thus ignoring potential dependencies.

**To Reproduce**
Run this tool on `package:firehose` in a monorepo at https://github.com/dart-lang/ecosystem/tree/main/pkgs/firehose, which has a `pubspec_overrides.yaml` with a local dependency

```yaml
dependency_overrides:
  dart_flutter_team_lints:
    path: ../dart_flutter_team_lints
```

**Actual and Expected behavior**
Some output on the diff.

**System info (please complete the following information):**
 - `Dart SDK version: 3.1.0 (stable) (Tue Aug 15 21:33:36 2023 +0000) on "linux_x64"`
 - `0.15.1-dev`

**Additional context**
